
services:
  postgres:
    image: postgres:16
    container_name: tm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tasksdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/001-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasksdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: tm-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  front:
    image: python:3.12-alpine
    container_name: tm-front-python
    working_dir: /app
    volumes:
      - ./front:/app:ro        # тут лежит твой index.html
    command: python -m http.server 5500 --bind 0.0.0.0
    ports:
      - "5500:5500"
    restart: unless-stopped
    # фронт из браузера ходит на http://localhost:8080 (как у тебя в JS), так что прокси не нужен

volumes:
  pgdata: